---
- name: ovn-kubernetes-types
  sync: true
  repo_link: "https://github.com/ovn-org/ovn-kubernetes"
  branch: master
  remote_api_directory: go-controller/pkg/crd/types
  local_api_directory: schemes/ovn/types
  excludes:
    - "*_test.go"
    - "*_webhook.go"
    - "testdata"

- name: ovn-kubernetes-routeadvertisement
  sync: true
  repo_link: "https://github.com/ovn-org/ovn-kubernetes"
  branch: master
  remote_api_directory: go-controller/pkg/crd/routeadvertisements/v1
  local_api_directory: schemes/ovn/routeadvertisement/v1
  replace_imports:
    - old: '"github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/types"'
      new: '"github.com/rh-ecosystem-edge/eco-goinfra/pkg/schemes/ovn/types"'
  excludes:
    - "*_test.go"
    - "*_webhook.go"
    - "testdata"
    - "apis"
...
